version: '3.8'

services:
   db:
      image: postgres:latest
      container_name: postgres_container
      ports:
         - "5433:5432"
      environment:
         - POSTGRES_USER=db_user
         - POSTGRES_PASSWORD=password
         - POSTGRES_DB=db
   
   backend:
      container_name: backend
      build:
         context: ./backend
      env_file:
          - ./backend/.env
      ports:  
         - "3001:3001"
      depends_on:
         - db
   frontend:
      container_name: frontend
      build:
         context: .
      env_file:
          - .env
      ports:  
         - "3000:3000"
      depends_on:
         - backend