# name: deploy the react js application to the aws ec2 instance.

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: "18"

#       - name: Install dependencies
#         run: npm install

#       - name: Build project
#         run: npm run build

#       - name: Deploy to EC2
#         uses: appleboy/ssh-action@v0.1.2
#         with:
#           host: ${{ secrets.IP }}
#           username: ${{ secrets.USER }}
#           key: ${{ secrets.PRIVATE_KEY }}
#           source: '.'
#           target: /home/ubuntu/app
#       - name: Restart server
#         run: ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} ${{ secrets.USER }}@${{ secrets.IP }} 'cd /home/ubuntu/app && pm2 restart all'


name: Deploy the React JS application to the AWS EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to the latest version
        with:
          node-version: "18"  # Update to the latest LTS version if needed

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Debug - List files after build
        run: ls -R  # Lists all files recursively to verify the build output

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10  # Updated to the latest version
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: .
          target: /home/ubuntu/app

      - name: Debug - Verify deployment on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} ${{ secrets.USER }}@${{ secrets.IP }} << 'EOF'
          echo "Current directory: $(pwd)"
          echo "Listing target directory:"
          ls -R /home/ubuntu/app
          EOF

      - name: Debug - Check PM2 status
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} ${{ secrets.USER }}@${{ secrets.IP }} << 'EOF'
          echo "Checking PM2 status:"
          pm2 status
          EOF

      - name: Restart server
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} ${{ secrets.USER }}@${{ secrets.IP }} << 'EOF'
          echo "Restarting PM2 processes:"
          cd /home/ubuntu/app
          pm2 restart all
          EOF

      - name: Debug - Verify PM2 restart
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.PRIVATE_KEY }} ${{ secrets.USER }}@${{ secrets.IP }} << 'EOF'
          echo "Verifying PM2 status after restart:"
          pm2 status
          EOF