name: Deploy the React JS application to the AWS EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"  # Use the latest LTS version if needed

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Debug - List files after build
        run: ls -R  # Lists all files recursively to verify the build output

      - name: Copy files to EC2 using SCP (Marketplace Action)
        uses: appleboy/scp-action@v0.1.6
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          source: "build/*"
          target: "/home/ubuntu/app"

      - name: Install Node.js and npm on EC2 (Marketplace Action)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            if ! command -v node &> /dev/null; then
              echo "Node.js is not installed. Installing Node.js and npm..."
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            else
              echo "Node.js is already installed."
            fi
            echo "Node.js version: $(node -v)"
            echo "npm version: $(npm -v)"

      - name: Install PM2 on EC2 (Marketplace Action)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            if ! command -v pm2 &> /dev/null; then
              echo "PM2 is not installed. Installing PM2..."
              sudo npm install -g pm2
            else
              echo "PM2 is already installed."
            fi
            echo "PM2 version: $(pm2 -v)"

      - name: Debug - Verify deployment on EC2 (Marketplace Action)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "Current directory: $(pwd)"
            echo "Listing target directory:"
            ls -R /home/ubuntu/app

      - name: Debug - Check PM2 status (Marketplace Action)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "Checking PM2 status:"
            pm2 status || echo "PM2 is not running any processes."

      - name: Restart server (Marketplace Action)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "Restarting PM2 processes:"
            cd /home/ubuntu/app
            pm2 restart all || echo "No PM2 processes to restart."

      - name: Debug - Verify PM2 restart (Marketplace Action)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            echo "Verifying PM2 status after restart:"
            pm2 status